import 'dotenv/config'

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { getPayload } from 'payload'
import sharp from 'sharp'

import config from '@/payload.config'

function relationshipID(value: unknown) {
  if (typeof value === 'string' || typeof value === 'number') return String(value)

  if (value && typeof value === 'object' && 'id' in value) {
    const id = value.id
    if (typeof id === 'string' || typeof id === 'number') return String(id)
  }

  return null
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const payload = await getPayload({ config })

try {
  const [mediaResult, boxedSetResult, locationResult, mythosResult, otherWorldResult] =
    await Promise.all([
      payload.find({
        collection: 'media',
        depth: 0,
        limit: 1000,
        overrideAccess: true,
      }),
      payload.find({
        collection: 'boxed-sets',
        depth: 0,
        limit: 1000,
        overrideAccess: true,
      }),
      payload.find({
        collection: 'locations',
        depth: 0,
        limit: 1000,
        overrideAccess: true,
      }),
      payload.find({
        collection: 'mythos-cards',
        depth: 0,
        limit: 1000,
        overrideAccess: true,
      }),
      payload.find({
        collection: 'other-worlds',
        depth: 0,
        limit: 1000,
        overrideAccess: true,
      }),
    ])
  const outputDirectory = path.resolve(process.cwd(), 'public', 'fixture-assets', 'game-data')
  const generatedFile = path.resolve(
    process.cwd(),
    'src',
    'fixtures',
    'gameDataMedia.generated.ts',
  )
  const usedKeys = new Set<string>()
  const mediaKeysByID = new Map<string, string>()
  const assets: {
    alt: string
    filename: string
    fixtureKey: string
    matchFilename: string
    publicPath: string
  }[] = []

  await mkdir(outputDirectory, { recursive: true })

  for (const media of mediaResult.docs) {
    if (!media.filename) {
      throw new Error(`Media ${media.id} has no filename.`)
    }

    const baseKey = media.assetKey || `media-${slugify(media.filename)}`
    let fixtureKey = baseKey
    let suffix = 2

    while (usedKeys.has(fixtureKey)) {
      fixtureKey = `${baseKey}-${suffix}`
      suffix += 1
    }

    usedKeys.add(fixtureKey)
    mediaKeysByID.set(String(media.id), fixtureKey)

    const targetFilename = `${fixtureKey}.webp`
    const sourcePath = path.resolve(process.cwd(), 'media', media.filename)
    const targetPath = path.join(outputDirectory, targetFilename)

    await sharp(sourcePath)
      .rotate()
      .resize({
        width: 1024,
        height: 1024,
        fit: 'inside',
        withoutEnlargement: true,
      })
      .webp({ quality: 85 })
      .toFile(targetPath)

    assets.push({
      fixtureKey,
      alt: media.alt || media.filename,
      filename: targetFilename,
      matchFilename: media.filename,
      publicPath: `/fixture-assets/game-data/${targetFilename}`,
    })
  }

  const mediaKey = (value: unknown) => {
    const id = relationshipID(value)
    return id ? mediaKeysByID.get(id) : undefined
  }
  const relationships = {
    boxedSetIcons: Object.fromEntries(
      boxedSetResult.docs
        .map((boxedSet) => [boxedSet.key, mediaKey(boxedSet.icon)])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    locationImages: Object.fromEntries(
      locationResult.docs
        .map((location) => [location.key, mediaKey(location.cardImage)])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    mythosLowerLeftImages: Object.fromEntries(
      mythosResult.docs
        .map((card) => [card.cardCode, mediaKey(card.lowerLeftOverride?.image)])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    otherWorldArt: Object.fromEntries(
      otherWorldResult.docs
        .map((world) => [world.key, mediaKey(world.art)])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
  }
  const source = `/* This file is generated by src/scripts/generateGameDataMediaFixture.ts. */\n\nexport const generatedGameDataMedia = ${JSON.stringify(
    {
      assets,
      relationships,
    },
    null,
    2,
  )} as const\n`

  await writeFile(generatedFile, source)
  payload.logger.info(
    `Generated ${assets.length} media fixture assets in ${outputDirectory}`,
  )
} finally {
  await payload.destroy()
}

process.exit(0)
