import 'dotenv/config'

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { getPayload } from 'payload'
import sharp from 'sharp'

import { buildGameDataSnapshot } from '@/fixtures/gameDataSnapshot'
import config from '@/payload.config'

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const payload = await getPayload({ config })

try {
  const mediaResult = await payload.find({
    collection: 'media',
    depth: 0,
    limit: 10000,
    overrideAccess: true,
  })
  const outputDirectory = path.resolve(process.cwd(), 'public', 'fixture-assets', 'game-data')
  const generatedMediaFile = path.resolve(
    process.cwd(),
    'src',
    'fixtures',
    'gameDataMedia.generated.ts',
  )
  const generatedSnapshotFile = path.resolve(
    process.cwd(),
    'src',
    'fixtures',
    'gameDataSnapshot.generated.ts',
  )
  const usedKeys = new Set<string>()
  const mediaKeysByID = new Map<string, string>()
  const assets: {
    alt: string
    filename: string
    fixtureKey: string
    matchFilename: string
    publicPath: string
  }[] = []

  await mkdir(outputDirectory, { recursive: true })

  for (const media of mediaResult.docs) {
    if (!media.filename) {
      throw new Error(`Media ${media.id} has no filename.`)
    }

    const baseKey = media.assetKey || `media-${slugify(media.filename)}`
    let fixtureKey = baseKey
    let suffix = 2

    while (usedKeys.has(fixtureKey)) {
      fixtureKey = `${baseKey}-${suffix}`
      suffix += 1
    }

    usedKeys.add(fixtureKey)
    mediaKeysByID.set(String(media.id), fixtureKey)

    const targetFilename = `${fixtureKey}.webp`
    const sourcePath = path.resolve(process.cwd(), 'media', media.filename)
    const targetPath = path.join(outputDirectory, targetFilename)

    await sharp(sourcePath)
      .rotate()
      .resize({
        width: 1024,
        height: 1024,
        fit: 'inside',
        withoutEnlargement: true,
      })
      .webp({ quality: 85 })
      .toFile(targetPath)

    assets.push({
      fixtureKey,
      alt: media.alt || media.filename,
      filename: targetFilename,
      matchFilename: media.filename,
      publicPath: `/fixture-assets/game-data/${targetFilename}`,
    })
  }

  assets.sort((left, right) => left.fixtureKey.localeCompare(right.fixtureKey))

  const snapshot = await buildGameDataSnapshot(payload, { mediaKeysByID })
  const {
    arkhamEncounterCards,
    ancientOnes,
    boxedSets,
    locations,
    mythosCards,
    neighborhoods,
    otherWorldEncounterCards,
    otherWorlds,
  } = snapshot.collections

  const relationships = {
    boxedSetIcons: Object.fromEntries(
      boxedSets
        .map((boxedSet) => [boxedSet.key, boxedSet.icon])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    locationImages: Object.fromEntries(
      locations
        .map((location) => [location.key, location.cardImage])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    mythosLowerLeftImages: Object.fromEntries(
      mythosCards
        .map((card) => [
          card.cardCode,
          (card.lowerLeftOverride as Record<string, unknown> | undefined)?.image,
        ])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
    otherWorldArt: Object.fromEntries(
      otherWorlds
        .map((world) => [world.key, world.art])
        .filter((entry): entry is [string, string] => Boolean(entry[1])),
    ),
  }
  const mediaSource = `/* This file is generated by src/scripts/generateGameDataMediaFixture.ts. */\n\nexport const generatedGameDataMedia = ${JSON.stringify(
    {
      assets,
      relationships,
    },
    null,
    2,
  )} as const\n`
  const snapshotSource = `/* This file is generated by src/scripts/generateGameDataMediaFixture.ts. */\n\nimport type { GameDataSnapshot } from './gameDataSnapshotTypes'\n\nexport const generatedGameDataSnapshot: GameDataSnapshot = ${JSON.stringify(
    snapshot,
    null,
    2,
  )} as const\n`

  await Promise.all([
    writeFile(generatedMediaFile, mediaSource),
    writeFile(generatedSnapshotFile, snapshotSource),
  ])
  payload.logger.info(
    `Snapshotted ${assets.length} media assets and ${
      boxedSets.length +
      ancientOnes.length +
      neighborhoods.length +
      locations.length +
      arkhamEncounterCards.length +
      mythosCards.length +
      otherWorlds.length +
      otherWorldEncounterCards.length
    } game documents.`,
  )
} finally {
  await payload.destroy()
}

process.exit(0)
