/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'boxed-sets': BoxedSet;
    'ancient-ones': AncientOne;
    neighborhoods: Neighborhood;
    locations: Location;
    'arkham-encounter-cards': ArkhamEncounterCard;
    'mythos-cards': MythosCard;
    'other-worlds': OtherWorld;
    'other-world-encounter-cards': OtherWorldEncounterCard;
    'game-sessions': GameSession;
    'fixture-installations': FixtureInstallation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'boxed-sets': BoxedSetsSelect<false> | BoxedSetsSelect<true>;
    'ancient-ones': AncientOnesSelect<false> | AncientOnesSelect<true>;
    neighborhoods: NeighborhoodsSelect<false> | NeighborhoodsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'arkham-encounter-cards': ArkhamEncounterCardsSelect<false> | ArkhamEncounterCardsSelect<true>;
    'mythos-cards': MythosCardsSelect<false> | MythosCardsSelect<true>;
    'other-worlds': OtherWorldsSelect<false> | OtherWorldsSelect<true>;
    'other-world-encounter-cards': OtherWorldEncounterCardsSelect<false> | OtherWorldEncounterCardsSelect<true>;
    'game-sessions': GameSessionsSelect<false> | GameSessionsSelect<true>;
    'fixture-installations': FixtureInstallationsSelect<false> | FixtureInstallationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  assetKey?: string | null;
  alt?: string | null;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxed-sets".
 */
export interface BoxedSet {
  id: string;
  name: string;
  /**
   * Stable identifier used by fixtures and saved games, for example "dunwich-horror".
   */
  key: string;
  category: 'core' | 'large-expansion' | 'small-expansion' | 'promotional' | 'custom';
  /**
   * Short fallback shown on cards when no icon has been uploaded.
   */
  abbreviation: string;
  /**
   * Counts toward the multiple-board investigator adjustment. Use for city boards such as Dunwich, Kingsport, and Innsmouth.
   */
  addsExpansionBoard: boolean;
  /**
   * Transparent PNG, WebP, or SVG mark used to identify this set on cards.
   */
  icon?: (string | null) | Media;
  sortOrder: number;
  /**
   * Alternate source names accepted by import and migration tools.
   */
  aliases?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ancient-ones".
 */
export interface AncientOne {
  id: string;
  name: string;
  /**
   * Stable identifier used by imports and saved games, for example "cthulhu".
   */
  key: string;
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Promotional'
    | 'Custom';
  /**
   * Set provenance and card icon.
   */
  sourceSet: string | BoxedSet;
  customSetName?: string | null;
  /**
   * Optional source lore. Gameplay instructions belong to a playable sheet.
   */
  lore?: string | null;
  sheets: {
    /**
     * Stable variant key such as "standard", "original", or "arkham-nights".
     */
    key: string;
    label: string;
    isDefault: boolean;
    doomTrack: number;
    combatRating: {
      display: string;
      type: 'fixed' | 'variable' | 'infinite';
      modifier?: number | null;
    };
    defenses?:
      | ('physical-resistance' | 'physical-immunity' | 'magical-resistance' | 'magical-immunity' | 'special')[]
      | null;
    defenseText: string;
    worshippers: string;
    powerName: string;
    power: string;
    startOfBattle?: string | null;
    attack: string;
    sheetImage?: (string | null) | Media;
    id?: string | null;
  }[];
  rulesNotes?:
    | {
        kind: 'clarification' | 'errata' | 'reference';
        text: string;
        /**
         * Optional variant key when this note applies to only one playable sheet.
         */
        sheetKey?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods".
 */
export interface Neighborhood {
  id: string;
  name: string;
  /**
   * Stable board-qualified identifier, for example "arkham-uptown".
   */
  key: string;
  board: 'Arkham' | 'Dunwich' | 'Kingsport' | 'Innsmouth' | 'Other';
  customBoardName?: string | null;
  /**
   * Printed deck colour, such as Red, Dark Grey, or Purple.
   */
  colourName?: string | null;
  /**
   * CSS fallback used when custom frame artwork is not available.
   */
  colourHex?: string | null;
  frontFrame?: (string | null) | Media;
  backFrame?: (string | null) | Media;
  sourceSet: string | BoxedSet;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  /**
   * Stable identifier used by cards and imports, for example "black-cave".
   */
  key: string;
  /**
   * Markdown-capable location label rendered on the Mythos card.
   */
  cardDisplayText: string;
  cardImage?: (string | null) | Media;
  board: 'Arkham' | 'Dunwich' | 'Kingsport' | 'Innsmouth' | 'Other';
  customBoardName?: string | null;
  neighborhood: string | Neighborhood;
  /**
   * Optional panel position on the neighbourhood deck back. Leave empty for areas that do not have their own artwork panel.
   */
  encounterBackOrder?: number | null;
  stability: 'stable' | 'unstable' | 'n/a';
  aquatic: boolean;
  encounterTypes?:
    | (
        | 'Ally'
        | 'Blessing'
        | 'Clue'
        | 'Common Item'
        | 'Money'
        | 'Sanity'
        | 'Skill'
        | 'Spell'
        | 'Stamina'
        | 'Unique Item'
      )[]
    | null;
  description?: string | null;
  specialEncounter?: string | null;
  homeInvestigators?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  /**
   * Set provenance and card icon.
   */
  sourceSet: string | BoxedSet;
  customSetName?: string | null;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arkham-encounter-cards".
 */
export interface ArkhamEncounterCard {
  id: string;
  /**
   * Stable internal identifier, for example "base-uptown-001".
   */
  cardCode: string;
  /**
   * Determines this card’s deck, colour, front frame, and card back.
   */
  neighborhood: string | Neighborhood;
  encounters: {
    location: string | Location;
    /**
     * Markdown is supported by the encounter card component.
     */
    text: string;
    id?: string | null;
  }[];
  sourceSet: string | BoxedSet;
  /**
   * Optional helper notes. These are not printed on the rendered card.
   */
  clarifications?: string | null;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mythos-cards".
 */
export interface MythosCard {
  id: string;
  title: string;
  /**
   * Stable identifier used by seeds and saved deck instances.
   */
  cardCode: string;
  copyCount: number;
  cardType:
    | 'Headline'
    | 'Environment'
    | 'Environment (Mystic)'
    | 'Environment (Urban)'
    | 'Environment (Weather)'
    | 'Rumor'
    | 'Special';
  desc?: string | null;
  flavorText?: string | null;
  effectText?: string | null;
  ongoingEffect?: string | null;
  passCondition?: string | null;
  failCondition?: string | null;
  /**
   * Printed clue placement text. Street areas remain text until board spaces are modeled.
   */
  clueText?: string | null;
  gateInstruction: {
    mode: 'none' | 'single' | 'choice' | 'all' | 'surge';
    /**
     * All printed gate destinations. Choice and all modes may contain multiple locations.
     */
    locations?: (string | Location)[] | null;
    burst?: boolean | null;
  };
  /**
   * Explicit doom-token instruction when the card differs from normal gate resolution.
   */
  doomTokens?: number | null;
  terrorIncrease?: number | null;
  reshuffleDeck?: boolean | null;
  specialInstruction?: string | null;
  rulesNotes?:
    | {
        kind: 'clarification' | 'errata' | 'misprint';
        text: string;
        id?: string | null;
      }[]
    | null;
  lowerLeftOverride?: {
    text?: string | null;
    image?: (string | null) | Media;
  };
  monsterMoveWhite?:
    | ('cross' | 'crescentMoon' | 'hexagon' | 'leftLean' | 'star' | 'triangle' | 'circle' | 'square' | 'diamond')[]
    | null;
  monsterMoveBlack?:
    | ('cross' | 'crescentMoon' | 'hexagon' | 'leftLean' | 'star' | 'triangle' | 'circle' | 'square' | 'diamond')[]
    | null;
  boxedset:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold';
  /**
   * Set provenance and card icon.
   */
  sourceSet: string | BoxedSet;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-worlds".
 */
export interface OtherWorld {
  id: string;
  name: string;
  /**
   * Stable identifier used by imports and game state, for example "abyss".
   */
  key: string;
  /**
   * Suggested encounter colours only. This does not restrict which cards can reference this world.
   */
  preferredColours?: ('blue' | 'green' | 'red' | 'yellow')[] | null;
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  /**
   * Set provenance and card icon.
   */
  sourceSet: string | BoxedSet;
  customSetName?: string | null;
  art?: (string | null) | Media;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-world-encounter-cards".
 */
export interface OtherWorldEncounterCard {
  id: string;
  /**
   * Stable internal identifier, for example "base-blue-001".
   */
  cardCode: string;
  colour: 'blue' | 'green' | 'red' | 'yellow';
  /**
   * The two named destination encounters and the single "Other" fallback printed on the card.
   */
  encounters: {
    isOther?: boolean | null;
    destination?: (string | null) | OtherWorld;
    /**
     * Markdown is supported by the existing card component.
     */
    text: string;
    id?: string | null;
  }[];
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  /**
   * Set provenance and card icon.
   */
  sourceSet: string | BoxedSet;
  customSetName?: string | null;
  /**
   * Optional helper notes. These are not printed on the rendered card.
   */
  clarifications?: string | null;
  fixtureNamespace?: string | null;
  fixtureVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions".
 */
export interface GameSession {
  id: string;
  name: string;
  status: 'active' | 'paused' | 'complete' | 'abandoned';
  playerCount: number;
  activeExpansions?:
    | (
        | 'Base Game'
        | 'Dunwich Horror'
        | 'Kingsport Horror'
        | 'Innsmouth Horror'
        | 'Miskatonic Horror'
        | 'Curse of the Dark Pharaoh (original)'
        | 'Curse of the Dark Pharaoh (Revised Edition)'
        | 'The Black Goat of the Woods'
        | 'The King in Yellow'
        | 'The Lurker at the Threshold'
      )[]
    | null;
  /**
   * Sets enabled for this saved game.
   */
  enabledSets: (string | BoxedSet)[];
  turnNumber: number;
  /**
   * Selected during setup and used to determine the session doom track.
   */
  activeAncientOne?: (string | null) | AncientOne;
  /**
   * The playable sheet variant selected for this session.
   */
  ancientOneSheetKey?: string | null;
  currentPhase:
    | 'Setup'
    | 'Opening Mythos'
    | 'Upkeep'
    | 'Movement'
    | 'Arkham Encounters'
    | 'Other World Encounters'
    | 'Mythos'
    | 'Final Battle';
  /**
   * Tracks completion of the opening Mythos draw before the first Upkeep phase.
   */
  openingHeadlineResolved: boolean;
  /**
   * Phase transitions used to restore the previous table phase without undoing game actions.
   */
  phaseHistory?:
    | {
        fromTurn: number;
        fromPhase:
          | 'Setup'
          | 'Opening Mythos'
          | 'Upkeep'
          | 'Movement'
          | 'Arkham Encounters'
          | 'Other World Encounters'
          | 'Mythos'
          | 'Final Battle';
        toTurn: number;
        toPhase:
          | 'Setup'
          | 'Opening Mythos'
          | 'Upkeep'
          | 'Movement'
          | 'Arkham Encounters'
          | 'Other World Encounters'
          | 'Mythos'
          | 'Final Battle';
        id?: string | null;
      }[]
    | null;
  /**
   * Player or investigator currently holding the first player marker.
   */
  firstPlayer?: string | null;
  tracks: {
    doomCurrent: number;
    doomMax?: number | null;
    terror: number;
    gatesOpen: number;
    elderSigns: number;
    monstersInArkham: number;
    monstersInOutskirts: number;
  };
  /**
   * Deck state for drawing without repeats. Shuffle events should rebuild the draw pile from the discard pile.
   */
  mythos: {
    /**
     * Cards still available to draw this cycle, in draw order.
     */
    drawPile?: (string | MythosCard)[] | null;
    /**
     * Resolved cards that can return to the deck after a shuffle event.
     */
    discardPile?: (string | MythosCard)[] | null;
    /**
     * Every Mythos card drawn during this session. This is preserved even after shuffles.
     */
    drawHistory?: (string | MythosCard)[] | null;
    /**
     * Copy-aware draw order. Each physical copy has its own stable instance key.
     */
    drawPileInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    discardPileInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    drawHistoryInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    /**
     * The card currently being revealed/resolved this Mythos phase.
     */
    currentDraw?: (string | null) | MythosCard;
    currentDrawInstanceKey?: string | null;
    currentDrawRevealed?: boolean | null;
    /**
     * Only one Environment card should be active at a time.
     */
    activeEnvironment?: (string | null) | MythosCard;
    activeEnvironmentInstanceKey?: string | null;
    /**
     * Only one Rumor card should be active at a time.
     */
    activeRumor?: (string | null) | MythosCard;
    activeRumorInstanceKey?: string | null;
    shuffleCount: number;
  };
  /**
   * Records when the discard pile was shuffled back into the draw pile.
   */
  shuffleEvents?:
    | {
        turnNumber?: number | null;
        phase?:
          | (
              | 'Setup'
              | 'Opening Mythos'
              | 'Upkeep'
              | 'Movement'
              | 'Arkham Encounters'
              | 'Other World Encounters'
              | 'Mythos'
              | 'Final Battle'
            )
          | null;
        reason: 'manual' | 'deck-empty' | 'card-effect' | 'setup';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Recoverable history for restore, undo, and table audit.
   */
  sessionLog?:
    | {
        turnNumber?: number | null;
        phase?:
          | (
              | 'Setup'
              | 'Opening Mythos'
              | 'Upkeep'
              | 'Movement'
              | 'Arkham Encounters'
              | 'Other World Encounters'
              | 'Mythos'
              | 'Final Battle'
            )
          | null;
        action:
          | 'create-session'
          | 'resume-session'
          | 'exit-session'
          | 'select-ancient-one'
          | 'advance-phase'
          | 'previous-phase'
          | 'draw-mythos'
          | 'reveal-card'
          | 'resolve-card'
          | 'activate-environment'
          | 'clear-environment'
          | 'activate-rumor'
          | 'pass-rumor'
          | 'fail-rumor'
          | 'discard-card'
          | 'shuffle-deck'
          | 'undo'
          | 'note';
        card?: (string | null) | MythosCard;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixture-installations".
 */
export interface FixtureInstallation {
  id: string;
  namespace: string;
  fixtureVersion: number;
  checksum: string;
  status: 'running' | 'succeeded' | 'failed';
  initiatedBy?: (string | null) | User;
  startedAt: string;
  completedAt?: string | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'boxed-sets';
        value: string | BoxedSet;
      } | null)
    | ({
        relationTo: 'ancient-ones';
        value: string | AncientOne;
      } | null)
    | ({
        relationTo: 'neighborhoods';
        value: string | Neighborhood;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'arkham-encounter-cards';
        value: string | ArkhamEncounterCard;
      } | null)
    | ({
        relationTo: 'mythos-cards';
        value: string | MythosCard;
      } | null)
    | ({
        relationTo: 'other-worlds';
        value: string | OtherWorld;
      } | null)
    | ({
        relationTo: 'other-world-encounter-cards';
        value: string | OtherWorldEncounterCard;
      } | null)
    | ({
        relationTo: 'game-sessions';
        value: string | GameSession;
      } | null)
    | ({
        relationTo: 'fixture-installations';
        value: string | FixtureInstallation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  assetKey?: T;
  alt?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxed-sets_select".
 */
export interface BoxedSetsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  category?: T;
  abbreviation?: T;
  addsExpansionBoard?: T;
  icon?: T;
  sortOrder?: T;
  aliases?:
    | T
    | {
        name?: T;
        id?: T;
      };
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ancient-ones_select".
 */
export interface AncientOnesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  boxedSet?: T;
  sourceSet?: T;
  customSetName?: T;
  lore?: T;
  sheets?:
    | T
    | {
        key?: T;
        label?: T;
        isDefault?: T;
        doomTrack?: T;
        combatRating?:
          | T
          | {
              display?: T;
              type?: T;
              modifier?: T;
            };
        defenses?: T;
        defenseText?: T;
        worshippers?: T;
        powerName?: T;
        power?: T;
        startOfBattle?: T;
        attack?: T;
        sheetImage?: T;
        id?: T;
      };
  rulesNotes?:
    | T
    | {
        kind?: T;
        text?: T;
        sheetKey?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods_select".
 */
export interface NeighborhoodsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  board?: T;
  customBoardName?: T;
  colourName?: T;
  colourHex?: T;
  frontFrame?: T;
  backFrame?: T;
  sourceSet?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  cardDisplayText?: T;
  cardImage?: T;
  board?: T;
  customBoardName?: T;
  neighborhood?: T;
  encounterBackOrder?: T;
  stability?: T;
  aquatic?: T;
  encounterTypes?: T;
  description?: T;
  specialEncounter?: T;
  homeInvestigators?:
    | T
    | {
        name?: T;
        id?: T;
      };
  boxedSet?: T;
  sourceSet?: T;
  customSetName?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "arkham-encounter-cards_select".
 */
export interface ArkhamEncounterCardsSelect<T extends boolean = true> {
  cardCode?: T;
  neighborhood?: T;
  encounters?:
    | T
    | {
        location?: T;
        text?: T;
        id?: T;
      };
  sourceSet?: T;
  clarifications?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mythos-cards_select".
 */
export interface MythosCardsSelect<T extends boolean = true> {
  title?: T;
  cardCode?: T;
  copyCount?: T;
  cardType?: T;
  desc?: T;
  flavorText?: T;
  effectText?: T;
  ongoingEffect?: T;
  passCondition?: T;
  failCondition?: T;
  clueText?: T;
  gateInstruction?:
    | T
    | {
        mode?: T;
        locations?: T;
        burst?: T;
      };
  doomTokens?: T;
  terrorIncrease?: T;
  reshuffleDeck?: T;
  specialInstruction?: T;
  rulesNotes?:
    | T
    | {
        kind?: T;
        text?: T;
        id?: T;
      };
  lowerLeftOverride?:
    | T
    | {
        text?: T;
        image?: T;
      };
  monsterMoveWhite?: T;
  monsterMoveBlack?: T;
  boxedset?: T;
  sourceSet?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-worlds_select".
 */
export interface OtherWorldsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  preferredColours?: T;
  boxedSet?: T;
  sourceSet?: T;
  customSetName?: T;
  art?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-world-encounter-cards_select".
 */
export interface OtherWorldEncounterCardsSelect<T extends boolean = true> {
  cardCode?: T;
  colour?: T;
  encounters?:
    | T
    | {
        isOther?: T;
        destination?: T;
        text?: T;
        id?: T;
      };
  boxedSet?: T;
  sourceSet?: T;
  customSetName?: T;
  clarifications?: T;
  fixtureNamespace?: T;
  fixtureVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions_select".
 */
export interface GameSessionsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  playerCount?: T;
  activeExpansions?: T;
  enabledSets?: T;
  turnNumber?: T;
  activeAncientOne?: T;
  ancientOneSheetKey?: T;
  currentPhase?: T;
  openingHeadlineResolved?: T;
  phaseHistory?:
    | T
    | {
        fromTurn?: T;
        fromPhase?: T;
        toTurn?: T;
        toPhase?: T;
        id?: T;
      };
  firstPlayer?: T;
  tracks?:
    | T
    | {
        doomCurrent?: T;
        doomMax?: T;
        terror?: T;
        gatesOpen?: T;
        elderSigns?: T;
        monstersInArkham?: T;
        monstersInOutskirts?: T;
      };
  mythos?:
    | T
    | {
        drawPile?: T;
        discardPile?: T;
        drawHistory?: T;
        drawPileInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        discardPileInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        drawHistoryInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        currentDraw?: T;
        currentDrawInstanceKey?: T;
        currentDrawRevealed?: T;
        activeEnvironment?: T;
        activeEnvironmentInstanceKey?: T;
        activeRumor?: T;
        activeRumorInstanceKey?: T;
        shuffleCount?: T;
      };
  shuffleEvents?:
    | T
    | {
        turnNumber?: T;
        phase?: T;
        reason?: T;
        note?: T;
        id?: T;
      };
  sessionLog?:
    | T
    | {
        turnNumber?: T;
        phase?: T;
        action?: T;
        card?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixture-installations_select".
 */
export interface FixtureInstallationsSelect<T extends boolean = true> {
  namespace?: T;
  fixtureVersion?: T;
  checksum?: T;
  status?: T;
  initiatedBy?: T;
  startedAt?: T;
  completedAt?: T;
  summary?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}