/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    locations: Location;
    'mythos-cards': MythosCard;
    'other-worlds': OtherWorld;
    'other-world-encounter-cards': OtherWorldEncounterCard;
    'game-sessions': GameSession;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'mythos-cards': MythosCardsSelect<false> | MythosCardsSelect<true>;
    'other-worlds': OtherWorldsSelect<false> | OtherWorldsSelect<true>;
    'other-world-encounter-cards': OtherWorldEncounterCardsSelect<false> | OtherWorldEncounterCardsSelect<true>;
    'game-sessions': GameSessionsSelect<false> | GameSessionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  /**
   * Stable identifier used by cards and imports, for example "black-cave".
   */
  key: string;
  /**
   * Markdown-capable location label rendered on the Mythos card.
   */
  cardDisplayText: string;
  cardImage?: (string | null) | Media;
  board: 'Arkham' | 'Dunwich' | 'Kingsport' | 'Innsmouth' | 'Other';
  customBoardName?: string | null;
  neighborhood: string;
  stability: 'stable' | 'unstable' | 'n/a';
  aquatic: boolean;
  encounterTypes?:
    | (
        | 'Ally'
        | 'Blessing'
        | 'Clue'
        | 'Common Item'
        | 'Money'
        | 'Sanity'
        | 'Skill'
        | 'Spell'
        | 'Stamina'
        | 'Unique Item'
      )[]
    | null;
  description?: string | null;
  specialEncounter?: string | null;
  homeInvestigators?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  customSetName?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mythos-cards".
 */
export interface MythosCard {
  id: string;
  title: string;
  /**
   * Stable identifier used by seeds and saved deck instances.
   */
  cardCode: string;
  copyCount: number;
  cardType:
    | 'Headline'
    | 'Environment'
    | 'Environment (Mystic)'
    | 'Environment (Urban)'
    | 'Environment (Weather)'
    | 'Rumor'
    | 'Special';
  desc?: string | null;
  flavorText?: string | null;
  effectText?: string | null;
  ongoingEffect?: string | null;
  passCondition?: string | null;
  failCondition?: string | null;
  /**
   * Printed clue placement text. Street areas remain text until board spaces are modeled.
   */
  clueText?: string | null;
  gateInstruction: {
    mode: 'none' | 'single' | 'choice' | 'all' | 'surge';
    /**
     * All printed gate destinations. Choice and all modes may contain multiple locations.
     */
    locations?: (string | Location)[] | null;
    burst?: boolean | null;
  };
  /**
   * Explicit doom-token instruction when the card differs from normal gate resolution.
   */
  doomTokens?: number | null;
  terrorIncrease?: number | null;
  reshuffleDeck?: boolean | null;
  specialInstruction?: string | null;
  rulesNotes?:
    | {
        kind: 'clarification' | 'errata' | 'misprint';
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy primary location retained while card rendering migrates to Gate Instruction.
   */
  location?: (string | null) | Location;
  lowerLeftOverride?: {
    text?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Legacy field retained until location relationships have been migrated.
   */
  encounterLocation: 'none' | 'The Witch House' | 'Unvisited Isle' | 'Black Cave';
  altLocationText?: string | null;
  altLocationImg?: string | null;
  monsterMoveWhite?:
    | ('cross' | 'crescentMoon' | 'hexagon' | 'leftLean' | 'star' | 'triangle' | 'circle' | 'square' | 'diamond')[]
    | null;
  monsterMoveBlack?:
    | ('cross' | 'crescentMoon' | 'hexagon' | 'leftLean' | 'star' | 'triangle' | 'circle' | 'square' | 'diamond')[]
    | null;
  boxedset:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-worlds".
 */
export interface OtherWorld {
  id: string;
  name: string;
  /**
   * Stable identifier used by imports and game state, for example "abyss".
   */
  key: string;
  /**
   * Suggested encounter colours only. This does not restrict which cards can reference this world.
   */
  preferredColours?: ('blue' | 'green' | 'red' | 'yellow')[] | null;
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  customSetName?: string | null;
  art?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-world-encounter-cards".
 */
export interface OtherWorldEncounterCard {
  id: string;
  /**
   * Stable internal identifier, for example "base-blue-001".
   */
  cardCode: string;
  colour: 'blue' | 'green' | 'red' | 'yellow';
  /**
   * The two named destination encounters and the single "Other" fallback printed on the card.
   */
  encounters: {
    isOther?: boolean | null;
    destination?: (string | null) | OtherWorld;
    /**
     * Markdown is supported by the existing card component.
     */
    text: string;
    id?: string | null;
  }[];
  boxedSet:
    | 'Base Game'
    | 'Dunwich Horror'
    | 'Kingsport Horror'
    | 'Innsmouth Horror'
    | 'Miskatonic Horror'
    | 'Curse of the Dark Pharaoh (original)'
    | 'Curse of the Dark Pharaoh (Revised Edition)'
    | 'The Black Goat of the Woods'
    | 'The King in Yellow'
    | 'The Lurker at the Threshold'
    | 'Custom';
  customSetName?: string | null;
  /**
   * Optional helper notes. These are not printed on the rendered card.
   */
  clarifications?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions".
 */
export interface GameSession {
  id: string;
  name: string;
  status: 'active' | 'paused' | 'complete' | 'abandoned';
  playerCount: number;
  activeExpansions?:
    | (
        | 'Base Game'
        | 'Dunwich Horror'
        | 'Kingsport Horror'
        | 'Innsmouth Horror'
        | 'Miskatonic Horror'
        | 'Curse of the Dark Pharaoh (original)'
        | 'Curse of the Dark Pharaoh (Revised Edition)'
        | 'The Black Goat of the Woods'
        | 'The King in Yellow'
        | 'The Lurker at the Threshold'
      )[]
    | null;
  turnNumber: number;
  currentPhase:
    | 'Setup'
    | 'Upkeep'
    | 'Movement'
    | 'Arkham Encounters'
    | 'Other World Encounters'
    | 'Mythos'
    | 'Final Battle';
  /**
   * Player or investigator currently holding the first player marker.
   */
  firstPlayer?: string | null;
  tracks: {
    doomCurrent: number;
    doomMax?: number | null;
    terror: number;
    gatesOpen: number;
    elderSigns: number;
    monstersInArkham: number;
    monstersInOutskirts: number;
  };
  /**
   * Deck state for drawing without repeats. Shuffle events should rebuild the draw pile from the discard pile.
   */
  mythos: {
    /**
     * Cards still available to draw this cycle, in draw order.
     */
    drawPile?: (string | MythosCard)[] | null;
    /**
     * Resolved cards that can return to the deck after a shuffle event.
     */
    discardPile?: (string | MythosCard)[] | null;
    /**
     * Every Mythos card drawn during this session. This is preserved even after shuffles.
     */
    drawHistory?: (string | MythosCard)[] | null;
    /**
     * Copy-aware draw order. Each physical copy has its own stable instance key.
     */
    drawPileInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    discardPileInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    drawHistoryInstances?:
      | {
          instanceKey: string;
          card: string | MythosCard;
          id?: string | null;
        }[]
      | null;
    /**
     * The card currently being revealed/resolved this Mythos phase.
     */
    currentDraw?: (string | null) | MythosCard;
    currentDrawInstanceKey?: string | null;
    currentDrawRevealed?: boolean | null;
    /**
     * Only one Environment card should be active at a time.
     */
    activeEnvironment?: (string | null) | MythosCard;
    activeEnvironmentInstanceKey?: string | null;
    /**
     * Only one Rumor card should be active at a time.
     */
    activeRumor?: (string | null) | MythosCard;
    activeRumorInstanceKey?: string | null;
    shuffleCount: number;
  };
  /**
   * Records when the discard pile was shuffled back into the draw pile.
   */
  shuffleEvents?:
    | {
        turnNumber?: number | null;
        phase?:
          | (
              | 'Setup'
              | 'Upkeep'
              | 'Movement'
              | 'Arkham Encounters'
              | 'Other World Encounters'
              | 'Mythos'
              | 'Final Battle'
            )
          | null;
        reason: 'manual' | 'deck-empty' | 'card-effect' | 'setup';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Recoverable history for restore, undo, and table audit.
   */
  sessionLog?:
    | {
        turnNumber?: number | null;
        phase?:
          | (
              | 'Setup'
              | 'Upkeep'
              | 'Movement'
              | 'Arkham Encounters'
              | 'Other World Encounters'
              | 'Mythos'
              | 'Final Battle'
            )
          | null;
        action:
          | 'draw-mythos'
          | 'reveal-card'
          | 'resolve-card'
          | 'activate-environment'
          | 'activate-rumor'
          | 'pass-rumor'
          | 'fail-rumor'
          | 'discard-card'
          | 'shuffle-deck'
          | 'undo'
          | 'note';
        card?: (string | null) | MythosCard;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'mythos-cards';
        value: string | MythosCard;
      } | null)
    | ({
        relationTo: 'other-worlds';
        value: string | OtherWorld;
      } | null)
    | ({
        relationTo: 'other-world-encounter-cards';
        value: string | OtherWorldEncounterCard;
      } | null)
    | ({
        relationTo: 'game-sessions';
        value: string | GameSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  cardDisplayText?: T;
  cardImage?: T;
  board?: T;
  customBoardName?: T;
  neighborhood?: T;
  stability?: T;
  aquatic?: T;
  encounterTypes?: T;
  description?: T;
  specialEncounter?: T;
  homeInvestigators?:
    | T
    | {
        name?: T;
        id?: T;
      };
  boxedSet?: T;
  customSetName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mythos-cards_select".
 */
export interface MythosCardsSelect<T extends boolean = true> {
  title?: T;
  cardCode?: T;
  copyCount?: T;
  cardType?: T;
  desc?: T;
  flavorText?: T;
  effectText?: T;
  ongoingEffect?: T;
  passCondition?: T;
  failCondition?: T;
  clueText?: T;
  gateInstruction?:
    | T
    | {
        mode?: T;
        locations?: T;
        burst?: T;
      };
  doomTokens?: T;
  terrorIncrease?: T;
  reshuffleDeck?: T;
  specialInstruction?: T;
  rulesNotes?:
    | T
    | {
        kind?: T;
        text?: T;
        id?: T;
      };
  location?: T;
  lowerLeftOverride?:
    | T
    | {
        text?: T;
        image?: T;
      };
  encounterLocation?: T;
  altLocationText?: T;
  altLocationImg?: T;
  monsterMoveWhite?: T;
  monsterMoveBlack?: T;
  boxedset?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-worlds_select".
 */
export interface OtherWorldsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  preferredColours?: T;
  boxedSet?: T;
  customSetName?: T;
  art?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-world-encounter-cards_select".
 */
export interface OtherWorldEncounterCardsSelect<T extends boolean = true> {
  cardCode?: T;
  colour?: T;
  encounters?:
    | T
    | {
        isOther?: T;
        destination?: T;
        text?: T;
        id?: T;
      };
  boxedSet?: T;
  customSetName?: T;
  clarifications?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions_select".
 */
export interface GameSessionsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  playerCount?: T;
  activeExpansions?: T;
  turnNumber?: T;
  currentPhase?: T;
  firstPlayer?: T;
  tracks?:
    | T
    | {
        doomCurrent?: T;
        doomMax?: T;
        terror?: T;
        gatesOpen?: T;
        elderSigns?: T;
        monstersInArkham?: T;
        monstersInOutskirts?: T;
      };
  mythos?:
    | T
    | {
        drawPile?: T;
        discardPile?: T;
        drawHistory?: T;
        drawPileInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        discardPileInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        drawHistoryInstances?:
          | T
          | {
              instanceKey?: T;
              card?: T;
              id?: T;
            };
        currentDraw?: T;
        currentDrawInstanceKey?: T;
        currentDrawRevealed?: T;
        activeEnvironment?: T;
        activeEnvironmentInstanceKey?: T;
        activeRumor?: T;
        activeRumorInstanceKey?: T;
        shuffleCount?: T;
      };
  shuffleEvents?:
    | T
    | {
        turnNumber?: T;
        phase?: T;
        reason?: T;
        note?: T;
        id?: T;
      };
  sessionLog?:
    | T
    | {
        turnNumber?: T;
        phase?: T;
        action?: T;
        card?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}